spring.application.name=edu-track
spring.data.mongodb.database=edutrackDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

# Enable detailed error logging and REST error messages
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.web=DEBUG
